backups:
  build: .
  dockerfile: Dockerfile
  container_name: backups
  restart: always
  environment:
    BKUP_LOGGER_CONSOLE_ENABLED: "true"
    BKUP_LOGGER_CONSOLE_LEVEL: "debug"
    BKUP_LOGGER_FILE_ENABLED: "false"
    BKUP_LOGGER_SYSLOG_ENABLED: "false"
    BKUP_BACKUP_URL: "s3://sm-snapshots@us-west-2/"
    BKUP_DELETE_OLD_SNAPSHOTS: "true"
    BKUP_EMAIL_ENABLED: "false"
  ports:
    - "80:3000"
  volumes:
    - /var/run/convoy:/var/run/convoy
