FROM ubuntu:16.04
RUN apt-get update && apt-get install wget && apt-get clean
RUN wget https://github.com/rancher/convoy/releases/download/v0.5.0/convoy.tar.gz && \
    tar xvzf convoy.tar.gz && \
    cp convoy/convoy convoy/convoy-pdata_tools /usr/local/bin/ && \
    rm -rf convoy* && \
    wget https://raw.githubusercontent.com/rancher/convoy/master/tools/dm_dev_partition.sh && \
    chmod +x dm_dev_partition.sh
ADD scripts/run.nfs.sh ./run.sh
CMD bash ./run.sh
